reviewers:
  defaults:
    - lijinfeng2011
    - openc3-bot-001

  groups:
    repository-owners:
      - lijinfeng2011
  
  per_author:
    engineers:
      - lijinfeng2011

files:
  '**':
    - repository-owners
  '**/*.yml':
    - repository-owners
  '.github/**':
    - repository-owners

options:
  ignore_draft: true
  ignored_keywords:
    - DO NOT REVIEW
  enable_group_assignment: false
  number_of_reviewers: 2
  last_files_match_only: false
